# NOTE: THIS SHOULD NOT BE CHECKED INTO GITHUB REPO

image: vmcsizer-docker-local.artifactory.eng.vmware.com/vmc-sizer-build:1.14

stages:
- test
- build
- publish

cache: {}

before_script:
- npm --unsafe-perm install --registry https://build-artifactory.eng.vmware.com/artifactory/api/npm/npm

test:unit:
  stage: test
  script:
  - echo "Run unit tests"
  - npm run test
  artifacts:
    paths:
    - coverage
    expire_in: 1 week
  when: always
  only:
  - pushes
  - web

build:transport:
  stage: build
  script:
  - echo "Building @vmw/transport"
  - npm run pre-publish
  artifacts:
    paths:
    - dist
    expire_in: 1 week
  when: on_success
  only:
  - pushes
  - web

publish:transport:
  stage: publish
  dependencies:
  - build:transport
  variables:
    GIT_AUTHOR_EMAIL: "kjosh@vmware.com"
    GIT_AUTHOR_NAME: "Josh Kim"
    PROJECT_ID: "33114"
    PROJECT_NAME: "EVE Portal UI"
    PROJECT_REPO: "gitlab.eng.vmware.com/project-eve/portal-ui.git"
  script:
  - echo "Configuring .npmrc"
  - ./build/scripts/configure-npmrc-on-ci.sh
  - echo "Publishing @vmw/transport"
  - npm run publish
  - echo "Proliferating to EVE Portal UI to create a merge request"
  - ./build/scripts/update-portal-ui-dep.sh
  when: manual
  only:
  - master
