image: node:latest

before_script:
  - install-chrome

test:
  script:
    - xvfb-run -a npm run test

#coverage:
#  script:
#    - xvfb-run -a npm run coverage
#
#prepare:
#  script:
#    - xvfb-run -a npm run prepare:all
