image: geekykaran/headless-chrome-node-docker:latest

stages:
- test
- build
- publish

cache: {}

before_script:
- npm install --registry https://build-artifactory.eng.vmware.com/artifactory/api/npm/npm

test:unit:
  stage: test
  script:
  - echo "Run unit tests"
  - npm run test
  artifacts:
    paths:
    - coverage
    expire_in: 1 week
  when: always
  only:
  - pushes
  - web

build:bifrost:
  stage: build
  script:
  - echo "Building @vmw/bifrost"
  - npm run prepare
  artifacts:
    paths:
    - dist
    expire_in: 1 week
  when: on_success
  only:
  - pushes
  - web

publish:bifrost:
  stage: publish
  dependencies:
  - build:bifrost
  script:
  - echo "Configuring .npmrc"
  - ./build/scripts/configure-npmrc-on-ci.sh
  - echo "Publishing @vmw/bifrost"
  - npm run publish
  when: manual
  only:
  - master
