image: geekykaran/headless-chrome-node-docker:latest

stages:
- test
- build
- publish

test:unit:
  stage: test
  script:
  - echo "Run unit tests"
  - npm install --registry https://build-artifactory.eng.vmware.com/artifactory/api/npm/npm
  - npm run test
  artifacts:
    paths:
    - coverage
    expire_in: 1 week
  when: always
  only:
  - pushes
  - web

build:bifrost:
  stage: build
  dependencies:
    - test:unit
  script:
  - echo "Building @vmw/bifrost"
  - npm run prepare
  artifacts:
    paths:
    - build/bifrost
    expire_in: 1 week
  when: on_success
  only:
  - pushes
  - web

publish:bifrost:
  stage: publish
  dependencies:
  - build:bifrost
  script:
  - echo "Publishing @vmw/bifrost"
  - npm run publish
  when: manual
  only:
  - master
