swagger: '2.0'
info:
  description: A list of CSP APIs used by VMC UI
  version: 1.0.0
  title: Common SaaS Platform API Documentation Center
host: vmc.vmware.com
basePath: /api/csp
tags:
  - name: roles
    description: Roles service
schemes:
  - http
produces:
  - application/json

paths:
  '/am/api/users/{userId}/orgs/{org}/service-roles':
    get:
      tags:
        - roles
      summary: Get Service Roles
      x-vmw-vapi-methodname: get
      x-vmc-ui-servicename: serviceRoles
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - $ref: '#/parameters/orgParam'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/RolesResponse'
        '404':
          description: Organization not found

    patch:
      tags:
        - roles
      summary: Update Service Roles
      operationId: patchServiceRoles
      x-vmw-vapi-methodname: patch
      x-vmc-ui-servicename: serviceRoles
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - $ref: '#/parameters/orgParam'
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/RolesPatchParams'
      responses:
        '200':
          description: User service roles updated
          schema:
            $ref: '#/definitions/RolesPatchResponse'
        '400':
          description: Invalid request body
        '404':
          description: User not found

definitions:
  RolesResponse:
    type: object
    properties:
      serviceRoles:
        type: array
        items:
          $ref: '#/definitions/ServiceRole'

  ServiceRole:
    type: object
    description: Roles object
    properties:
      serviceDefinitionLink:
        type: string
        description: Service Definition Link
      serviceRoleNames:
        type: array
        description: List of role names for this user
        items:
          type: string

  RolesPatchParams:
    type: object
    properties:
      serviceDefinitionLink:
        type: string
        description: Service Definition Link
      roleNamesToRemove:
        type: array
        description: Array of role names to remove
        items:
          type: string
      roleNamesToAdd:
        type: array
        description: Array of role names to add
        items:
          type: string

  RolesPatchResponse:
    type: object
    properties:
      serviceDefinitionLink:
        type: string
        description: Service Definition Link
      roleNamesToRemove:
        type: array
        description: Array of role names to remove
        items:
          type: string
      roleNamesToAdd:
        type: array
        description: Array of role names to add
        items:
          type: string
parameters:
  orgParam:
    name: org
    in: path
    description: Organization identifier
    required: true
    type: string
